name: claimscope_clean
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  
  flutter:
   sdk: flutter
  flutter_localizations:
   sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  vector_math: ^2.1.4
  geolocator: ^13.0.4
  firebase_analytics: ^12.0.4
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pdf: ^3.10.8
  image_picker: ^1.1.2
  cloud_functions: ^6.0.4
  url_launcher: ^6.3.2
  firebase_storage: ^13.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
  assets:
    - assets/Icon/logo.png 



    